# Generated by Django 5.1.6 on 2025-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
