# Generated by Django 5.1.6 on 2025-02-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookmanagement", "0003_student_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_book",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="Bookmanagement.author",
            ),
        ),
    ]
