# Generated by Django 5.1.6 on 2025-02-21 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookmanagement", "0004_book_total_book_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="student",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issuebook",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
